In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [50]:
print("Task #1")
x = np.array([0,2,4,6,8,1,3,5,7,9], dtype=float)
print(f"Values of x: {x}", f"Size x: {x.size}")

Task #1
Values of x: [0. 2. 4. 6. 8. 1. 3. 5. 7. 9.] Size x: 10


In [87]:
print("Task #2")
m = np.zeros((3, 3), dtype=int)
print("Matrix 3x3")
print(m, f"Size m: {m.size}", f"Shape m: {m.shape}")

Task #2
Matrix 3x3
[[0 0 0]
 [0 0 0]
 [0 0 0]] Size m: 9 Shape m: (3, 3)


In [52]:
print("Task #3")
m = np.array([
    [1,1,1,1,1],
    [1,2,3,4,5],
    [1,3,6,10,4],
    [1,4,10,6,3],
    [1,5,4,3,2]], dtype=int)
print("Matrix 5x5")
print(m, f"Size m: {m.size}", f"Shape m: {m.shape}")

Task #3
Matrix 5x5
[[ 1  1  1  1  1]
 [ 1  2  3  4  5]
 [ 1  3  6 10  4]
 [ 1  4 10  6  3]
 [ 1  5  4  3  2]] Size m: 25 Shape m: (5, 5)


In [53]:
print("Task #4")
m = np.random.randint(0, 2, size=(4, 4))
print("Matrix random 4x4")
print(m, f"Size m: {m.size}", f"Shape m: {m.shape}")

Task #4
Matrix random 4x4
[[1 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 1 1 1]] Size m: 16 Shape m: (4, 4)


In [54]:
print("Task #5")
x = np.random.randint(1, 11, size=(5))
y = np.random.randint(1, 11, size=(5))
print(f"Values of x: {x}")
print(f"Values of y: {y}")
print(f"Addition: {x+y}")
print(f"Subtraction: {x-y}")
print(f"Multiplication: {x*y}")

Task #5
Values of x: [5 6 8 8 6]
Values of y: [3 1 6 2 9]
Addition: [ 8  7 14 10 15]
Subtraction: [ 2  5  2  6 -3]
Multiplication: [15  6 48 16 54]


In [64]:
print("Task #6")
x = np.random.randint(1, 11, size=(7))
y = np.random.randint(1, 11, size=(7))
print(f"Values of x: {x}", f"Size x: {x.size}")
print(f"Values of y: {y}", f"Size y: {y.size}")
print(f": {np.dot(x,y)}")

Task #6
Values of x: [ 9 10  3 10  6  2  2] Size x: 7
Values of y: [ 9  3  6  7 10  7  5] Size y: 7
Scalar product: 283


In [56]:
print("Task #7")
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 3))
print("Matrix random 2x2")
print(x, f"Size x: {x.size}", f"Shape x: {x.shape}")
print("Matrix random 2x3")
print(y, f"Size y: {y.size}", f"Shape y: {y.shape}")
print(f"Scalar product:\n{np.dot(x,y)}")

Task #7
Matrix random 2x2
[[7 9]
 [8 9]] Size x: 4 Shape x: (2, 2)
Matrix random 2x3
[[4 2 7]
 [5 8 6]] Size y: 6 Shape y: (2, 3)
Multiplication:
[[ 73  86 103]
 [ 77  88 110]]


In [61]:
print("Task #8")
x = np.random.randint(0, 2, size=(3, 3))
print("Matrix random 3x3")
print(x, f"Size: {x.size}", f"Shape: {x.shape}")
print("Inverse matrix")
y = np.linalg.inv(x)
print(y, f"Size: {y.size}", f"Shape: {y.shape}")

Task #8
Matrix random 3x3
[[1 0 0]
 [1 1 0]
 [0 0 1]] Size: 9 Shape: (3, 3)
Inverse matrix
[[ 1.  0.  0.]
 [-1.  1.  0.]
 [ 0.  0.  1.]] Size: 9 Shape: (3, 3)


In [62]:
print("Task #9")
x = np.random.randint(0, 2, size=(4, 4))
print("Matrix random 4x4")
print(x, f"Size: {x.size}", f"Shape: {x.shape}")
print("Matrix transposition")
print(x.T, f"Size: {x.size}", f"Shape: {x.shape}")

Task #9
Matrix random 4x4
[[1 1 0 1]
 [0 0 0 1]
 [0 1 1 1]
 [1 1 0 1]] Size: 16 Shape: (4, 4)
Matrix transposition
[[1 0 0 1]
 [1 0 1 1]
 [0 0 1 0]
 [1 1 1 1]] Size: 16 Shape: (4, 4)


In [68]:
print("Task #10")
x = np.random.randint(1, 11, size=(3, 4))
y = np.random.randint(1, 11, size=(4))
print("Matrix random 3x4")
print(x, f"Size: {x.size}", f"Shape: {x.shape}")
print(f"Values of y:\n {y}", f"Size y: {y.size}")
print(f"Multiplication:\n{x*y}")

Task #10
Matrix random 3x4
[[10  6 10  2]
 [10  9  6  4]
 [ 3  1  3  9]] Size: 12 Shape: (3, 4)
Values of y:
 [10  3  7  5] Size y: 4
Multiplication:
[[100  18  70  10]
 [100  27  42  20]
 [ 30   3  21  45]]


In [72]:
print("Task #11")
x = np.random.randint(0, 2, size=(2, 3))
y = np.random.randint(0, 2, size=(3))
print("Matrix random 2x3")
print(x, f"Size: {x.size}", f"Shape: {x.shape}")
print(f"Values of y:\n {y}", f"Size y: {y.size}")
print(f"Multiplication:\n{x*y}")

Task #11
Matrix random 2x3
[[1 0 1]
 [0 0 1]] Size: 6 Shape: (2, 3)
Values of y:
 [1 0 1] Size y: 3
Multiplication:
[[1 0 1]
 [0 0 1]]


In [71]:
print("Task #12")
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
print("Matrix random 2x2")
print(x, f"Size x: {x.size}", f"Shape x: {x.shape}")
print("Matrix random 2x2")
print(y, f"Size y: {y.size}", f"Shape y: {y.shape}")
print(f"Multiplication:\n{x*y}")

Task #12
Matrix random 2x2
[[9 3]
 [2 1]] Size x: 4 Shape x: (2, 2)
Matrix random 2x2
[[8 5]
 [5 4]] Size y: 4 Shape y: (2, 2)
Multiplication:
[[72 15]
 [10  4]]


In [73]:
print("Task #13")
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
print("Matrix random 2x2")
print(x, f"Size x: {x.size}", f"Shape x: {x.shape}")
print("Matrix random 2x2")
print(y, f"Size y: {y.size}", f"Shape y: {y.shape}")
print(f"Scalar product:\n{np.dot(x,y)}")

Task #13
Matrix random 2x2
[[5 2]
 [7 2]] Size x: 4 Shape x: (2, 2)
Matrix random 2x2
[[4 7]
 [9 4]] Size y: 4 Shape y: (2, 2)
Scalar product:
[[38 43]
 [46 57]]


In [76]:
print("Task #14")
m = np.random.randint(1, 101, size=(5, 5))
print("Matrix random 5x5")
print(m, f"Size m: {m.size}", f"Shape m: {m.shape}")
print(f"The sum of matrix elements:\n {m.sum()}")

Task #14
Matrix random 5x5
[[39 42  5 69 51]
 [18 69 84 57 81]
 [11 28 26 67 42]
 [ 4 96 68 33 19]
 [82  6 74 26 37]] Size m: 25 Shape m: (5, 5)
The sum of matrix elements:
 1134


In [79]:
print("Task #15")
x = np.random.randint(1, 11, size=(4, 4))
y = np.random.randint(1, 11, size=(4, 4))
print("Matrix random 4x4")
print(x, f"Size x: {x.size}", f"Shape x: {x.shape}")
print("Matrix random 4x4")
print(y, f"Size y: {y.size}", f"Shape y: {y.shape}")
print(f"Matrix difference:\n{x-y}")

Task #15
Matrix random 4x4
[[ 6  2  7  5]
 [ 4  8  9 10]
 [ 2  6  3 10]
 [ 4  8  8  3]] Size x: 16 Shape x: (4, 4)
Matrix random 4x4
[[ 4  1  6  3]
 [ 4  5  6  3]
 [ 4  7  1  3]
 [10 10  6  8]] Size y: 16 Shape y: (4, 4)
Matrix difference:
[[ 2  1  1  2]
 [ 0  3  3  7]
 [-2 -1  2  7]
 [-6 -2  2 -5]]


In [91]:
print("Task #16")
x = np.random.randint(0, 2, size=(3, 3))
print("Matrix random 3x3")
print(x, f"Size: {x.size}", f"Shape: {x.shape}")
y = [[x[0].sum()],
     [x[1].sum()],
     [x[2].sum()]]
print(f"A column vector containing the sum of the elements of each row of the matrix:\n {y}")

Task #16
Matrix random 3x3
[[0 1 1]
 [1 1 1]
 [0 0 0]] Size: 9 Shape: (3, 3)
A column vector containing the sum of the elements of each row of the matrix:
 [[2], [3], [0]]


In [93]:
print("Task #17")
x = np.random.randint(1, 11, size=(3, 4))
print("Matrix random 3x4")
print(x, f"Size: {x.size}", f"Shape: {x.shape}")
print("Squared matrix 3x4")
print(np.square(x))

Task #17
Matrix random 3x4
[[10  9  4  2]
 [ 8  3 10  5]
 [ 5  3  3 10]] Size: 12 Shape: (3, 4)
Squared matrix 3x4
[[100  81  16   4]
 [ 64   9 100  25]
 [ 25   9   9 100]]


In [95]:
print("Task #18")
x = np.random.randint(1, 51, size=(4))
print("Matrix random 3x4")
print(f"Values of x: {x}", f"Size x: {x.size}")
print("Square root vector")
print(np.sqrt(x))

Task #18
Matrix random 3x4
Values of x: [22  5 32 31] Size x: 4
Square root vector
[4.69041576 2.23606798 5.65685425 5.56776436]
